### ISSUE TITLE
problem when Render Depth for DSLR and iPhone

### ISSUE THREAD

**Issue by miaolin968** [scannetpp/scannetpp#118]
I meet this problem when render depth for dslr.
`python -m common.render common/configs/render.yml`
It seems related to OpenGL, but I don't know how to address this problrm
`(renderpy) (base) root@interactive3810:/opt/data/private/scannetpp-main# python -m common.render common/configs/render.yml
scene:   0%|                                                                                                                | 0/1 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "/root/miniconda3/envs/renderpy/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/root/miniconda3/envs/renderpy/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/opt/data/private/msl/model/4D/scannetpp-main/common/render.py", line 90, in <module>
    main(args)
  File "/opt/data/private/msl/model/4D/scannetpp-main/common/render.py", line 48, in main
    render_engine = renderpy.Render()
RuntimeError: Failed to initialize EGL`

**Comment by cy94** [comment]
Do you have a GPU?
