### ISSUE TITLE
Download Error

### ISSUE THREAD

**Issue by XiangFeng66** [scannetpp/scannetpp#68]
Encountered a problem while downloading 
Traceback (most recent call last):
  File "D:\data_download\download_scannetpp.py", line 181, in <module>
    main(args)
  File "D:\data_download\download_scannetpp.py", line 158, in main
    with zipfile.ZipFile(tgt_download_path, 'r') as zip_ref:
  File "D:\Anaconda\envs\fengxiangNerf\lib\zipfile.py", line 1248, in __init__
    self.fp = io.open(file, filemode)
FileNotFoundError: [Errno 2] No such file or directory: 'D:\\data\\56a0ec536c\\dslr\\resized_images.zip', what is the reason?

**Comment by cy94** [comment]
The download script hasn't been tested on Windows. You have to change the backward slashes to forward slashes in the download URL to download the file first. Could you try that out?

________________________________
From: Xiang Feng ***@***.***>
Sent: 01 March 2024 10:04:05
To: scannetpp/scannetpp
Cc: Subscribed
Subject: [scannetpp/scannetpp] Download Error (Issue #68)


Encountered a problem while downloading
Traceback (most recent call last):
File "D:\data_download\download_scannetpp.py", line 181, in
main(args)
File "D:\data_download\download_scannetpp.py", line 158, in main
with zipfile.ZipFile(tgt_download_path, 'r') as zip_ref:
File "D:\Anaconda\envs\fengxiangNerf\lib\zipfile.py", line 1248, in init
self.fp = io.open(file, filemode)
FileNotFoundError: [Errno 2] No such file or directory: 'D:\data\56a0ec536c\dslr\resized_images.zip', what is the reason?

**Comment by XiangFeng66** [comment]
Thank you very much for your help, it means a lot to me.
